[package]
name = "dtlearn"
version = "0.1.0"
edition = "2018"

[lib]
name = "dtlearn"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.23.0"
strum_macros = "0.23"
pretty_assertions = "1.0.0"